name: iFoodProcess
options:
  minimumXcodeGenVersion: 2.0
  groupSortPosition: top
  generateEmptyDirectories: true
  bundleIdPrefix: com.gbrlcm.processoseletivo
  deploymentTarget:
    iOS: "15.0"
settings:
    DEVELOPMENT_TEAM: WK7599VNDW
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.0.1
localPackages:
  - ./Modules/StartUp
  - ./Modules/DependencyInjection
  - ./Modules/RouterImplementation
  - ./Modules/RouterInterface
  - ./Modules/Home
  - ./Modules/PullRequest
  - ./Modules/WebView
  - ./Modules/Models
  - ./Modules/Network
  - ./Modules/ReducerCore
  - ./Modules/DesignSystem

targets:
    App:
        type: application
        platform: iOS
        postCompileScripts:
              name: Swift Lint
              script: |
                if [[ "$(uname -m)" == arm64 ]]
                then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if command -v swiftlint >/dev/null 2>&1
                then
                    swiftlint
                else
                    echo "warning: `swiftlint` command not found - See https://github.com/realm/SwiftLint#installation for installation instructions."
                fi
        sources:
            - path: App
        dependencies:
            - package: StartUp
        scheme:
            gatherCoverageData: true
            testTargets:
                - package: Home/HomeTests
                - package: Network/NetworkTests
                - package: RouterImplementation/RouterImplementationTests
                - package: ReducerCore/ReducerCoreTests
                - package: WebView/WebViewTests
